# Generated by Django 3.2 on 2021-08-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagerelease',
            name='project',
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='projects',
            field=models.ManyToManyField(related_name='packages', related_query_name='package', to='api.Project'),
        ),
    ]
